### PR TITLE
output: fix misuse of unsafe.Pointer

### LINKED ISSUE #18: Go pointer passing restriction violated in out_multiinstance?
> A Go function called by C code may take C pointers as arguments, and it may store non-pointer or C pointer data through those pointers, but **it may not store a Go pointer in memory pointed to by a C pointer.** - https://golang.org/cmd/cgo/#hdr-Passing_pointers (emphasis mine)

In the `out_multiinstance` example, pointer of the Go string `id` is stored in memory pointed to by a C pointer (`plugin` argument of FLBPluginInit) in `FLBPluginSetContext`, which I think violates the restrictions on passing pointers between Go and C.

### PR DESCRIPTION
**Pull request by l2dy**
Waste a byte of memory on each `FLBPluginSetContext`, but I think it's acceptable.

Closes #18.

### CODE REVIEW

File: output/output.go [hunk 1]
```diff
@@ -69,15 +69,15 @@ func FLBPluginConfigKey(plugin unsafe.Pointer, key string) string {
 	return value
 }
 
-var contexts []interface{}
+var contexts = make(map[uintptr]interface{})
 
 func FLBPluginSetContext(plugin unsafe.Pointer, ctx interface{}) {
-	i := len(contexts)
-	contexts = append(contexts, ctx)
+	i := unsafe.Pointer(C.CString(""))
```
Comment (wfernandes) [inline output/output.go]: Can you add some comments explaining what's happening here? Thanks.

Comment (l2dy) [reply output/output.go]: Done.

**Comment by l2dy** [comment]
@wfernandes Any updates?

**Comment by l2dy** [comment]
@edsiper Can you help assign someone to review this PR?

**Comment by wfernandes** [comment]
Apologies for the delay. @l2dy 
I haven't had any time to test this myself. I had asked some colleagues to verify this work but they haven't yet gotten back to me. 
I'm thinking i'll just merge this in since it looks good.

/cc @edsiper
